### ISSUE TITLE
Make map interactive

### ISSUE THREAD

**Issue by fdenoodt** [oSoc18/healthdata#11]
with leaflet

**Comment by QingzhiHu** [comment]
please check: https://github.com/perrygeo/leaflet-simple-csv

**Comment by QingzhiHu** [comment]
A quick tutorial you need: https://maptimeboston.github.io/leaflet-intro/

**Comment by QingzhiHu** [comment]
check this if you need to get more maps: https://www.mapbox.com/account/access-tokens/
free key

**Comment by archived-m** [comment]
Covered in React version of the map
