### ISSUE TITLE
Store general information of a hospital

### ISSUE THREAD

**Issue by nvdk** [oSoc18/healthdata#37]
For each hospital we should store:
- lat, lng
- address
- telephone number
- website
- name

**Comment by Pizzibee** [comment]
Pseudo-Code (self-note) : 
- Get xls from api (https://fair-acc.healthdata.be/dataset/804931be-a5de-4512-9d7a-e549ea20e383)
- Convert xls to csv
- Import csv to database after comparing the data already in the db
